import logging
import uuid
from typing import Any, Dict, List
from app.db.session import db_context
from app.graph.state import ChatState
from app.memory.store import ConversationStore
from app.memory.summarizer import ConversationSummarizer
from shared.schemas.chat import ActionLink, CitationItem

from app.retrieval.cache import RedisCache
from app.graph.support import clean_suggestions

logger = logging.getLogger(__name__)
conv_store = ConversationStore()
summarizer = ConversationSummarizer()
answer_cache = RedisCache()


async def finalize_node(state: ChatState) -> Dict[str, Any]:
    conv_id_str = state.get("conversation_id")
    final_answer = state.get("final_answer", "")
    citations = state.get("citations") or []
    citations_data = [c.model_dump() if hasattr(c, "model_dump") else c for c in citations]
    
    # Suggestions are generated by the router from the current query. Never
    # fall back to generic service chips that can be unrelated to the answer.
    suggestions: List[str] = clean_suggestions(state.get("suggestions") or [])

    # Action links
    action_links: List[ActionLink] = []
    for link_obj in state.get("shortcut_links") or []:
        action_links.append(ActionLink(label=link_obj.get("label", "لینک"), url=link_obj.get("url", "")))

    if not action_links:
        action_links.append(ActionLink(label="کنسول لیارا", url="https://console.liara.ir"))
        action_links.append(ActionLink(label="مستندات کامل", url="https://docs.liara.ir"))

    # Persist in DB
    message_id = 0
    if conv_id_str:
        try:
            conv_uuid = uuid.UUID(conv_id_str)
            async with db_context() as session:
                # 1. Store user message first if not yet stored
                user_msg = state.get("message", "")
                await conv_store.append_message(
                    session=session,
                    conversation_id=conv_uuid,
                    role="user",
                    content=user_msg,
                )

                # 2. Store assistant message
                msg_row = await conv_store.append_message(
                    session=session,
                    conversation_id=conv_uuid,
                    role="assistant",
                    content=final_answer,
                    citations=citations_data,
                    route=state.get("action"),
                    confidence=1.0 if state.get("confidence") == "high" else 0.5,
                    prompt_tokens=state.get("tokens_prompt", 0),
                    completion_tokens=state.get("tokens_completion", 0),
                    cost_usd=state.get("cost_usd", 0.0),
                    latency_ms=state.get("latency_ms", 0),
                    trace_id=state.get("trace_id"),
                )
                message_id = msg_row.id

                # 3. Cache answer for identical future queries (<5ms response)
                if state.get("confidence") == "high" and not state.get("is_shortcut"):
                    await answer_cache.set_cached_answer(
                        query=user_msg,
                        data={
                            "answer": final_answer,
                            "citations": citations_data,
                            "suggestions": suggestions,
                            "action_links": [l.model_dump() if hasattr(l, "model_dump") else l for l in action_links],
                            "confidence": "high",
                        },
                        ttl_seconds=86400 * 3,
                    )

                # 4. Check for rolling summary update
                conv = await conv_store.get_or_create_conversation(
                    session=session,
                    conversation_id=conv_id_str,
                    site_key=state.get("site_key", "pk_live_docs_liara_ir"),
                )
                await summarizer.maybe_update_summary(session, conv)
        except Exception as e:
            logger.error(f"Error persisting message to database: {e}", exc_info=True)

    # Print detailed latency breakdown report
    timings = dict(state.get("timings") or {})
    total_time = sum(timings.values())
    breakdown_lines = [f"  - {step}: {duration * 1000:.1f} ms" for step, duration in timings.items()]
    breakdown_str = "\n".join(breakdown_lines)

    logger.info(
        f"\n========== CHAT TURN LATENCY BREAKDOWN ==========\n"
        f"Total Turn Time: {total_time * 1000:.1f} ms ({total_time:.2f} s)\n"
        f"Action: {state.get('action', 'search')}\n"
        f"Step Latencies:\n{breakdown_str}\n"
        f"================================================="
    )

    return {
        "message_id": message_id,
        "suggestions": suggestions,
        "action_links": action_links,
        "timings": timings,
    }
